# Generated by Django 3.0 on 2020-11-16 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_auto_20201112_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='місто')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='область')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Області',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='worker/', verbose_name='фото користувача')),
                ('describe', models.TextField()),
                ('created', models.DateField(auto_now_add=True, verbose_name='створено')),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('cities', models.ManyToManyField(related_name='workersincity', to='user.City', verbose_name='місто')),
                ('subcategories', models.ManyToManyField(related_name='workers', to='job.SubCategoryJob', verbose_name='підкатегорія')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Worker')),
                ('name', models.CharField(max_length=125, verbose_name='назва компанії')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='адреса компанії')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанії',
            },
            bases=('user.worker',),
        ),
        migrations.CreateModel(
            name='WorkerGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=user.models.user_directory_path)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workimages', to='user.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='майстерність')),
                ('workers', models.ManyToManyField(related_name='skilltags', to='user.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, verbose_name='номер телефону')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='user.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='user.Region', verbose_name='область'),
        ),
    ]
