# Generated by Django 3.0 on 2020-11-12 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Категорія роботи',
                'verbose_name_plural': 'Категорії для роботи',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='job.CategoryJob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
