# Generated by Django 3.0 on 2020-11-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoryjob',
            options={'verbose_name': 'Підкатегорія для роботи', 'verbose_name_plural': 'Підкатегорії для роботи'},
        ),
    ]
